type: object
required:
  - exchange
  - marketType
  - instrument
  - channels
  - startImmediately
properties:
  exchange:
    type: string
  marketType:
    type: string
  instrument:
    $ref: "./CreateStreamInstrument.yaml"
  channels:
    type: array
    items:
      $ref: "./StreamChannelConfig.yaml"
  startImmediately:
    type: boolean
  autoRestart:
    type: boolean
    default: false
