[versions]
springBoot = "4.1.1"
springDependencyManagement = "1.1.7"
openapiGenerator = "7.25.0"
slf4j = "2.0.16"
jacksonNullable = "0.2.12"
swaggerAnnotations = "2.2.22"
mapstruct = "1.6.3"
lombok = "1.18.34"
resilience4j = "2.4.0"

[libraries]
springBom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jakartaValidationApi = { module = "jakarta.validation:jakarta.validation-api" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
springWeb = { module = "org.springframework:spring-web" }
springContext = { module = "org.springframework:spring-context" }
jacksonDatabind = { module = "tools.jackson.core:jackson-databind" }
jacksonCore = { module = "tools.jackson.core:jackson-core" }
springBootStarterWebmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
springBootStarterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
springBootStarterValidation = { module = "org.springframework.boot:spring-boot-starter-validation" }
springBootStarterAspectj = { module = "org.springframework.boot:spring-boot-starter-aspectj" }
springBootStarterJdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc" }
springBootStarterDataJdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test" }
springBootHttpClient = { module = "org.springframework.boot:spring-boot-http-client" }
postgresql = { module = "org.postgresql:postgresql" }
openapiJacksonNullable = { module = "org.openapitools:jackson-databind-nullable", version.ref = "jacksonNullable" }
swaggerAnnotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swaggerAnnotations" }
jakartaAnnotationApi = { module = "jakarta.annotation:jakarta.annotation-api" }
jakartaServletApi = { module = "jakarta.servlet:jakarta.servlet-api" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstructProcessor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
resilience4jSpringBoot4 = { module = "io.github.resilience4j:resilience4j-spring-boot4", version.ref = "resilience4j" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
openapiGenerator = { id = "org.openapi.generator", version.ref = "openapiGenerator" }
