type: object
required:
  - symbol
  - baseAsset
  - quoteAsset
  - instrumentId
properties:
  symbol:
    type: string
  baseAsset:
    type: string
  quoteAsset:
    type: string
  instrumentId:
    type: string
