type: object
required:
  - code
  - displayName
  - enabled
  - channels
properties:
  code:
    type: string
  displayName:
    type: string
  enabled:
    type: boolean
  channels:
    type: array
    items:
      $ref: "../channel/Channel.yaml"