type: object
required:
  - instrument
  - channels
  - startImmediately
properties:
  instrument:
    $ref: './InstrumentId.yaml'
  channels:
    type: array
    items:
      $ref: "../channel/Channel.yaml"
  startImmediately:
    type: boolean