type: object
required:
  - exchange
  - market
  - baseAsset
  - quoteAsset
properties:
  exchange:
    type: string
  market:
      type: string
  baseAsset:
    type: string
  quoteAsset:
    type: string

