type: object
required:
  - streamId
  - instrument
  - desiredState
  - channels
  - status
properties:
  streamId:
    type: string
    example: "binance-spot-btc-usdt"
  instrument:
    $ref: "./StreamInstrument.yaml"
  desiredState:
    $ref: "./StreamState.yaml"
  channels:
    type: array
    items:
      $ref: "../channel/ChannelSelection.yaml"
  status:
    $ref: "./StreamStatus.yaml"
